# Generated by Django 4.2.30 on 2026-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='blog_images/default.jpg', upload_to='blog_images/'),
        ),
    ]
